# Automatically generated by Pynguin.
import pynguin_triangle1 as module_0


def test_case_0():
    int_0 = 1311
    str_0 = module_0.triangle(int_0, int_0, int_0)
    assert str_0 == 'Equilateral triangle'


def test_case_1():
    int_0 = None
    str_0 = module_0.triangle(int_0, int_0, int_0)
    assert str_0 == 'Not a triangle'
    int_1 = 3807
    int_2 = None
    int_3 = 3676
    str_1 = module_0.triangle(int_1, int_2, int_3)
    assert str_1 == 'Not a triangle'


def test_case_2():
    int_0 = -808
    int_1 = 1311
    str_0 = module_0.triangle(int_1, int_1, int_1)
    assert str_0 == 'Equilateral triangle'
    str_1 = module_0.triangle(int_0, int_0, int_0)
    assert str_1 == 'Not a triangle'


def test_case_3():
    int_0 = -2222
    int_1 = 1556
    str_0 = module_0.triangle(int_0, int_0, int_1)
    assert str_0 == 'Not a triangle'


def test_case_4():
    int_0 = -2942
    int_1 = -487
    str_0 = module_0.triangle(int_0, int_1, int_1)
    assert str_0 == 'Not a triangle'


def test_case_5():
    int_0 = 684
    int_1 = 3659
    str_0 = module_0.triangle(int_1, int_0, int_1)
    assert str_0 == 'Isosceles triangle'
    int_2 = 2373
    int_3 = None
    int_4 = 3023
    str_1 = module_0.triangle(int_2, int_3, int_4)
    assert str_1 == 'Not a triangle'
    str_2 = module_0.triangle(int_0, int_1, int_1)
    assert str_2 == 'Isosceles triangle'


def test_case_6():
    int_0 = 2337
    int_1 = 157
    str_0 = module_0.triangle(int_0, int_0, int_1)
    assert str_0 == 'Isosceles triangle'


def test_case_7():
    int_0 = 695
    int_1 = 561
    str_0 = module_0.triangle(int_0, int_1, int_1)
    assert str_0 == 'Isosceles triangle'
    int_2 = 433
    str_1 = module_0.triangle(int_2, int_2, int_0)
    assert str_1 == 'Isosceles triangle'
    str_2 = module_0.triangle(int_0, int_0, int_1)
    assert str_2 == 'Isosceles triangle'
    str_3 = module_0.triangle(int_1, int_1, int_0)
    assert str_3 == 'Isosceles triangle'
    str_4 = module_0.triangle(int_0, int_1, int_1)
    assert str_4 == 'Isosceles triangle'
    str_5 = module_0.triangle(int_2, int_0, int_1)
    assert str_5 == 'Scalene triangle'
    int_3 = -2354
    str_6 = module_0.triangle(int_3, int_0, int_3)
    assert str_6 == 'Not a triangle'
    int_4 = 35
    str_7 = module_0.triangle(int_2, int_0, int_0)
    assert str_7 == 'Isosceles triangle'
    str_8 = module_0.triangle(int_0, int_4, int_0)
    assert str_8 == 'Isosceles triangle'
    str_9 = module_0.triangle(int_0, int_1, int_4)
    assert str_9 == 'Not a triangle'
